name: Trigger auto deployment for f1fantasyapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/f1fantasyapp-AutoDeployTrigger-26c0e302-8d46-4433-9e3a-637a82b6108a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.F1FANTASYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.F1FANTASYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.F1FANTASYAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.F1FANTASYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.F1FANTASYAPP_REGISTRY_PASSWORD }}
          containerAppName: f1fantasyapp
          resourceGroup: F1FantasyApp
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


